// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_medication.proto

package rpc;

public final class RpcMedication {
  private RpcMedication() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PatientOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Patient)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 patientId = 1;</code>
     * @return The patientId.
     */
    long getPatientId();
  }
  /**
   * Protobuf type {@code Patient}
   */
  public  static final class Patient extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Patient)
      PatientOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Patient.newBuilder() to construct.
    private Patient(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Patient() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Patient();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Patient(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              patientId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rpc.RpcMedication.internal_static_Patient_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rpc.RpcMedication.internal_static_Patient_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rpc.RpcMedication.Patient.class, rpc.RpcMedication.Patient.Builder.class);
    }

    public static final int PATIENTID_FIELD_NUMBER = 1;
    private long patientId_;
    /**
     * <code>int64 patientId = 1;</code>
     * @return The patientId.
     */
    public long getPatientId() {
      return patientId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (patientId_ != 0L) {
        output.writeInt64(1, patientId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (patientId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, patientId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rpc.RpcMedication.Patient)) {
        return super.equals(obj);
      }
      rpc.RpcMedication.Patient other = (rpc.RpcMedication.Patient) obj;

      if (getPatientId()
          != other.getPatientId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PATIENTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPatientId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rpc.RpcMedication.Patient parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rpc.RpcMedication.Patient parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rpc.RpcMedication.Patient parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rpc.RpcMedication.Patient parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rpc.RpcMedication.Patient parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rpc.RpcMedication.Patient parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rpc.RpcMedication.Patient parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rpc.RpcMedication.Patient parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static rpc.RpcMedication.Patient parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static rpc.RpcMedication.Patient parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rpc.RpcMedication.Patient parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rpc.RpcMedication.Patient parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rpc.RpcMedication.Patient prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Patient}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Patient)
        rpc.RpcMedication.PatientOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rpc.RpcMedication.internal_static_Patient_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rpc.RpcMedication.internal_static_Patient_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rpc.RpcMedication.Patient.class, rpc.RpcMedication.Patient.Builder.class);
      }

      // Construct using rpc.RpcMedication.Patient.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        patientId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rpc.RpcMedication.internal_static_Patient_descriptor;
      }

      @java.lang.Override
      public rpc.RpcMedication.Patient getDefaultInstanceForType() {
        return rpc.RpcMedication.Patient.getDefaultInstance();
      }

      @java.lang.Override
      public rpc.RpcMedication.Patient build() {
        rpc.RpcMedication.Patient result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public rpc.RpcMedication.Patient buildPartial() {
        rpc.RpcMedication.Patient result = new rpc.RpcMedication.Patient(this);
        result.patientId_ = patientId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rpc.RpcMedication.Patient) {
          return mergeFrom((rpc.RpcMedication.Patient)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rpc.RpcMedication.Patient other) {
        if (other == rpc.RpcMedication.Patient.getDefaultInstance()) return this;
        if (other.getPatientId() != 0L) {
          setPatientId(other.getPatientId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        rpc.RpcMedication.Patient parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (rpc.RpcMedication.Patient) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long patientId_ ;
      /**
       * <code>int64 patientId = 1;</code>
       * @return The patientId.
       */
      public long getPatientId() {
        return patientId_;
      }
      /**
       * <code>int64 patientId = 1;</code>
       * @param value The patientId to set.
       * @return This builder for chaining.
       */
      public Builder setPatientId(long value) {
        
        patientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 patientId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPatientId() {
        
        patientId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Patient)
    }

    // @@protoc_insertion_point(class_scope:Patient)
    private static final rpc.RpcMedication.Patient DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rpc.RpcMedication.Patient();
    }

    public static rpc.RpcMedication.Patient getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Patient>
        PARSER = new com.google.protobuf.AbstractParser<Patient>() {
      @java.lang.Override
      public Patient parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Patient(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Patient> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Patient> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public rpc.RpcMedication.Patient getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Med)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string medName = 1;</code>
     * @return The medName.
     */
    java.lang.String getMedName();
    /**
     * <code>string medName = 1;</code>
     * @return The bytes for medName.
     */
    com.google.protobuf.ByteString
        getMedNameBytes();

    /**
     * <code>string startHour = 2;</code>
     * @return The startHour.
     */
    java.lang.String getStartHour();
    /**
     * <code>string startHour = 2;</code>
     * @return The bytes for startHour.
     */
    com.google.protobuf.ByteString
        getStartHourBytes();

    /**
     * <code>string endHour = 3;</code>
     * @return The endHour.
     */
    java.lang.String getEndHour();
    /**
     * <code>string endHour = 3;</code>
     * @return The bytes for endHour.
     */
    com.google.protobuf.ByteString
        getEndHourBytes();
  }
  /**
   * Protobuf type {@code Med}
   */
  public  static final class Med extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Med)
      MedOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Med.newBuilder() to construct.
    private Med(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Med() {
      medName_ = "";
      startHour_ = "";
      endHour_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Med();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Med(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              medName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              startHour_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              endHour_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rpc.RpcMedication.internal_static_Med_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rpc.RpcMedication.internal_static_Med_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rpc.RpcMedication.Med.class, rpc.RpcMedication.Med.Builder.class);
    }

    public static final int MEDNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object medName_;
    /**
     * <code>string medName = 1;</code>
     * @return The medName.
     */
    public java.lang.String getMedName() {
      java.lang.Object ref = medName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        medName_ = s;
        return s;
      }
    }
    /**
     * <code>string medName = 1;</code>
     * @return The bytes for medName.
     */
    public com.google.protobuf.ByteString
        getMedNameBytes() {
      java.lang.Object ref = medName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        medName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STARTHOUR_FIELD_NUMBER = 2;
    private volatile java.lang.Object startHour_;
    /**
     * <code>string startHour = 2;</code>
     * @return The startHour.
     */
    public java.lang.String getStartHour() {
      java.lang.Object ref = startHour_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        startHour_ = s;
        return s;
      }
    }
    /**
     * <code>string startHour = 2;</code>
     * @return The bytes for startHour.
     */
    public com.google.protobuf.ByteString
        getStartHourBytes() {
      java.lang.Object ref = startHour_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startHour_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENDHOUR_FIELD_NUMBER = 3;
    private volatile java.lang.Object endHour_;
    /**
     * <code>string endHour = 3;</code>
     * @return The endHour.
     */
    public java.lang.String getEndHour() {
      java.lang.Object ref = endHour_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endHour_ = s;
        return s;
      }
    }
    /**
     * <code>string endHour = 3;</code>
     * @return The bytes for endHour.
     */
    public com.google.protobuf.ByteString
        getEndHourBytes() {
      java.lang.Object ref = endHour_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endHour_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMedNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, medName_);
      }
      if (!getStartHourBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, startHour_);
      }
      if (!getEndHourBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, endHour_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMedNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, medName_);
      }
      if (!getStartHourBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, startHour_);
      }
      if (!getEndHourBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, endHour_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rpc.RpcMedication.Med)) {
        return super.equals(obj);
      }
      rpc.RpcMedication.Med other = (rpc.RpcMedication.Med) obj;

      if (!getMedName()
          .equals(other.getMedName())) return false;
      if (!getStartHour()
          .equals(other.getStartHour())) return false;
      if (!getEndHour()
          .equals(other.getEndHour())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MEDNAME_FIELD_NUMBER;
      hash = (53 * hash) + getMedName().hashCode();
      hash = (37 * hash) + STARTHOUR_FIELD_NUMBER;
      hash = (53 * hash) + getStartHour().hashCode();
      hash = (37 * hash) + ENDHOUR_FIELD_NUMBER;
      hash = (53 * hash) + getEndHour().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rpc.RpcMedication.Med parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rpc.RpcMedication.Med parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rpc.RpcMedication.Med parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rpc.RpcMedication.Med parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rpc.RpcMedication.Med parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rpc.RpcMedication.Med parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rpc.RpcMedication.Med parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rpc.RpcMedication.Med parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static rpc.RpcMedication.Med parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static rpc.RpcMedication.Med parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rpc.RpcMedication.Med parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rpc.RpcMedication.Med parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rpc.RpcMedication.Med prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Med}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Med)
        rpc.RpcMedication.MedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rpc.RpcMedication.internal_static_Med_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rpc.RpcMedication.internal_static_Med_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rpc.RpcMedication.Med.class, rpc.RpcMedication.Med.Builder.class);
      }

      // Construct using rpc.RpcMedication.Med.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        medName_ = "";

        startHour_ = "";

        endHour_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rpc.RpcMedication.internal_static_Med_descriptor;
      }

      @java.lang.Override
      public rpc.RpcMedication.Med getDefaultInstanceForType() {
        return rpc.RpcMedication.Med.getDefaultInstance();
      }

      @java.lang.Override
      public rpc.RpcMedication.Med build() {
        rpc.RpcMedication.Med result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public rpc.RpcMedication.Med buildPartial() {
        rpc.RpcMedication.Med result = new rpc.RpcMedication.Med(this);
        result.medName_ = medName_;
        result.startHour_ = startHour_;
        result.endHour_ = endHour_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rpc.RpcMedication.Med) {
          return mergeFrom((rpc.RpcMedication.Med)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rpc.RpcMedication.Med other) {
        if (other == rpc.RpcMedication.Med.getDefaultInstance()) return this;
        if (!other.getMedName().isEmpty()) {
          medName_ = other.medName_;
          onChanged();
        }
        if (!other.getStartHour().isEmpty()) {
          startHour_ = other.startHour_;
          onChanged();
        }
        if (!other.getEndHour().isEmpty()) {
          endHour_ = other.endHour_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        rpc.RpcMedication.Med parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (rpc.RpcMedication.Med) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object medName_ = "";
      /**
       * <code>string medName = 1;</code>
       * @return The medName.
       */
      public java.lang.String getMedName() {
        java.lang.Object ref = medName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          medName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string medName = 1;</code>
       * @return The bytes for medName.
       */
      public com.google.protobuf.ByteString
          getMedNameBytes() {
        java.lang.Object ref = medName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          medName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string medName = 1;</code>
       * @param value The medName to set.
       * @return This builder for chaining.
       */
      public Builder setMedName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        medName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string medName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMedName() {
        
        medName_ = getDefaultInstance().getMedName();
        onChanged();
        return this;
      }
      /**
       * <code>string medName = 1;</code>
       * @param value The bytes for medName to set.
       * @return This builder for chaining.
       */
      public Builder setMedNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        medName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object startHour_ = "";
      /**
       * <code>string startHour = 2;</code>
       * @return The startHour.
       */
      public java.lang.String getStartHour() {
        java.lang.Object ref = startHour_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          startHour_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string startHour = 2;</code>
       * @return The bytes for startHour.
       */
      public com.google.protobuf.ByteString
          getStartHourBytes() {
        java.lang.Object ref = startHour_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          startHour_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string startHour = 2;</code>
       * @param value The startHour to set.
       * @return This builder for chaining.
       */
      public Builder setStartHour(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        startHour_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string startHour = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartHour() {
        
        startHour_ = getDefaultInstance().getStartHour();
        onChanged();
        return this;
      }
      /**
       * <code>string startHour = 2;</code>
       * @param value The bytes for startHour to set.
       * @return This builder for chaining.
       */
      public Builder setStartHourBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        startHour_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object endHour_ = "";
      /**
       * <code>string endHour = 3;</code>
       * @return The endHour.
       */
      public java.lang.String getEndHour() {
        java.lang.Object ref = endHour_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          endHour_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string endHour = 3;</code>
       * @return The bytes for endHour.
       */
      public com.google.protobuf.ByteString
          getEndHourBytes() {
        java.lang.Object ref = endHour_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          endHour_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string endHour = 3;</code>
       * @param value The endHour to set.
       * @return This builder for chaining.
       */
      public Builder setEndHour(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        endHour_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string endHour = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEndHour() {
        
        endHour_ = getDefaultInstance().getEndHour();
        onChanged();
        return this;
      }
      /**
       * <code>string endHour = 3;</code>
       * @param value The bytes for endHour to set.
       * @return This builder for chaining.
       */
      public Builder setEndHourBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        endHour_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Med)
    }

    // @@protoc_insertion_point(class_scope:Med)
    private static final rpc.RpcMedication.Med DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rpc.RpcMedication.Med();
    }

    public static rpc.RpcMedication.Med getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Med>
        PARSER = new com.google.protobuf.AbstractParser<Med>() {
      @java.lang.Override
      public Med parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Med(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Med> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Med> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public rpc.RpcMedication.Med getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TakenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Taken)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string medName = 1;</code>
     * @return The medName.
     */
    java.lang.String getMedName();
    /**
     * <code>string medName = 1;</code>
     * @return The bytes for medName.
     */
    com.google.protobuf.ByteString
        getMedNameBytes();

    /**
     * <code>int64 patientId = 2;</code>
     * @return The patientId.
     */
    long getPatientId();

    /**
     * <code>bool isTaken = 3;</code>
     * @return The isTaken.
     */
    boolean getIsTaken();
  }
  /**
   * Protobuf type {@code Taken}
   */
  public  static final class Taken extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Taken)
      TakenOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Taken.newBuilder() to construct.
    private Taken(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Taken() {
      medName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Taken();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Taken(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              medName_ = s;
              break;
            }
            case 16: {

              patientId_ = input.readInt64();
              break;
            }
            case 24: {

              isTaken_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rpc.RpcMedication.internal_static_Taken_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rpc.RpcMedication.internal_static_Taken_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rpc.RpcMedication.Taken.class, rpc.RpcMedication.Taken.Builder.class);
    }

    public static final int MEDNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object medName_;
    /**
     * <code>string medName = 1;</code>
     * @return The medName.
     */
    public java.lang.String getMedName() {
      java.lang.Object ref = medName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        medName_ = s;
        return s;
      }
    }
    /**
     * <code>string medName = 1;</code>
     * @return The bytes for medName.
     */
    public com.google.protobuf.ByteString
        getMedNameBytes() {
      java.lang.Object ref = medName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        medName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PATIENTID_FIELD_NUMBER = 2;
    private long patientId_;
    /**
     * <code>int64 patientId = 2;</code>
     * @return The patientId.
     */
    public long getPatientId() {
      return patientId_;
    }

    public static final int ISTAKEN_FIELD_NUMBER = 3;
    private boolean isTaken_;
    /**
     * <code>bool isTaken = 3;</code>
     * @return The isTaken.
     */
    public boolean getIsTaken() {
      return isTaken_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMedNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, medName_);
      }
      if (patientId_ != 0L) {
        output.writeInt64(2, patientId_);
      }
      if (isTaken_ != false) {
        output.writeBool(3, isTaken_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMedNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, medName_);
      }
      if (patientId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, patientId_);
      }
      if (isTaken_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isTaken_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rpc.RpcMedication.Taken)) {
        return super.equals(obj);
      }
      rpc.RpcMedication.Taken other = (rpc.RpcMedication.Taken) obj;

      if (!getMedName()
          .equals(other.getMedName())) return false;
      if (getPatientId()
          != other.getPatientId()) return false;
      if (getIsTaken()
          != other.getIsTaken()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MEDNAME_FIELD_NUMBER;
      hash = (53 * hash) + getMedName().hashCode();
      hash = (37 * hash) + PATIENTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPatientId());
      hash = (37 * hash) + ISTAKEN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsTaken());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rpc.RpcMedication.Taken parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rpc.RpcMedication.Taken parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rpc.RpcMedication.Taken parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rpc.RpcMedication.Taken parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rpc.RpcMedication.Taken parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rpc.RpcMedication.Taken parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rpc.RpcMedication.Taken parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rpc.RpcMedication.Taken parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static rpc.RpcMedication.Taken parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static rpc.RpcMedication.Taken parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rpc.RpcMedication.Taken parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rpc.RpcMedication.Taken parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rpc.RpcMedication.Taken prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Taken}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Taken)
        rpc.RpcMedication.TakenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rpc.RpcMedication.internal_static_Taken_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rpc.RpcMedication.internal_static_Taken_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rpc.RpcMedication.Taken.class, rpc.RpcMedication.Taken.Builder.class);
      }

      // Construct using rpc.RpcMedication.Taken.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        medName_ = "";

        patientId_ = 0L;

        isTaken_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rpc.RpcMedication.internal_static_Taken_descriptor;
      }

      @java.lang.Override
      public rpc.RpcMedication.Taken getDefaultInstanceForType() {
        return rpc.RpcMedication.Taken.getDefaultInstance();
      }

      @java.lang.Override
      public rpc.RpcMedication.Taken build() {
        rpc.RpcMedication.Taken result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public rpc.RpcMedication.Taken buildPartial() {
        rpc.RpcMedication.Taken result = new rpc.RpcMedication.Taken(this);
        result.medName_ = medName_;
        result.patientId_ = patientId_;
        result.isTaken_ = isTaken_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rpc.RpcMedication.Taken) {
          return mergeFrom((rpc.RpcMedication.Taken)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rpc.RpcMedication.Taken other) {
        if (other == rpc.RpcMedication.Taken.getDefaultInstance()) return this;
        if (!other.getMedName().isEmpty()) {
          medName_ = other.medName_;
          onChanged();
        }
        if (other.getPatientId() != 0L) {
          setPatientId(other.getPatientId());
        }
        if (other.getIsTaken() != false) {
          setIsTaken(other.getIsTaken());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        rpc.RpcMedication.Taken parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (rpc.RpcMedication.Taken) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object medName_ = "";
      /**
       * <code>string medName = 1;</code>
       * @return The medName.
       */
      public java.lang.String getMedName() {
        java.lang.Object ref = medName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          medName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string medName = 1;</code>
       * @return The bytes for medName.
       */
      public com.google.protobuf.ByteString
          getMedNameBytes() {
        java.lang.Object ref = medName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          medName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string medName = 1;</code>
       * @param value The medName to set.
       * @return This builder for chaining.
       */
      public Builder setMedName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        medName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string medName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMedName() {
        
        medName_ = getDefaultInstance().getMedName();
        onChanged();
        return this;
      }
      /**
       * <code>string medName = 1;</code>
       * @param value The bytes for medName to set.
       * @return This builder for chaining.
       */
      public Builder setMedNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        medName_ = value;
        onChanged();
        return this;
      }

      private long patientId_ ;
      /**
       * <code>int64 patientId = 2;</code>
       * @return The patientId.
       */
      public long getPatientId() {
        return patientId_;
      }
      /**
       * <code>int64 patientId = 2;</code>
       * @param value The patientId to set.
       * @return This builder for chaining.
       */
      public Builder setPatientId(long value) {
        
        patientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 patientId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPatientId() {
        
        patientId_ = 0L;
        onChanged();
        return this;
      }

      private boolean isTaken_ ;
      /**
       * <code>bool isTaken = 3;</code>
       * @return The isTaken.
       */
      public boolean getIsTaken() {
        return isTaken_;
      }
      /**
       * <code>bool isTaken = 3;</code>
       * @param value The isTaken to set.
       * @return This builder for chaining.
       */
      public Builder setIsTaken(boolean value) {
        
        isTaken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isTaken = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsTaken() {
        
        isTaken_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Taken)
    }

    // @@protoc_insertion_point(class_scope:Taken)
    private static final rpc.RpcMedication.Taken DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rpc.RpcMedication.Taken();
    }

    public static rpc.RpcMedication.Taken getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Taken>
        PARSER = new com.google.protobuf.AbstractParser<Taken>() {
      @java.lang.Override
      public Taken parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Taken(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Taken> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Taken> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public rpc.RpcMedication.Taken getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Empty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code Empty}
   */
  public  static final class Empty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Empty)
      EmptyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Empty.newBuilder() to construct.
    private Empty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Empty() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Empty();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Empty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rpc.RpcMedication.internal_static_Empty_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rpc.RpcMedication.internal_static_Empty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rpc.RpcMedication.Empty.class, rpc.RpcMedication.Empty.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rpc.RpcMedication.Empty)) {
        return super.equals(obj);
      }
      rpc.RpcMedication.Empty other = (rpc.RpcMedication.Empty) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rpc.RpcMedication.Empty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rpc.RpcMedication.Empty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rpc.RpcMedication.Empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rpc.RpcMedication.Empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rpc.RpcMedication.Empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rpc.RpcMedication.Empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rpc.RpcMedication.Empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rpc.RpcMedication.Empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static rpc.RpcMedication.Empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static rpc.RpcMedication.Empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rpc.RpcMedication.Empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rpc.RpcMedication.Empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rpc.RpcMedication.Empty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Empty)
        rpc.RpcMedication.EmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rpc.RpcMedication.internal_static_Empty_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rpc.RpcMedication.internal_static_Empty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rpc.RpcMedication.Empty.class, rpc.RpcMedication.Empty.Builder.class);
      }

      // Construct using rpc.RpcMedication.Empty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rpc.RpcMedication.internal_static_Empty_descriptor;
      }

      @java.lang.Override
      public rpc.RpcMedication.Empty getDefaultInstanceForType() {
        return rpc.RpcMedication.Empty.getDefaultInstance();
      }

      @java.lang.Override
      public rpc.RpcMedication.Empty build() {
        rpc.RpcMedication.Empty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public rpc.RpcMedication.Empty buildPartial() {
        rpc.RpcMedication.Empty result = new rpc.RpcMedication.Empty(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rpc.RpcMedication.Empty) {
          return mergeFrom((rpc.RpcMedication.Empty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rpc.RpcMedication.Empty other) {
        if (other == rpc.RpcMedication.Empty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        rpc.RpcMedication.Empty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (rpc.RpcMedication.Empty) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Empty)
    }

    // @@protoc_insertion_point(class_scope:Empty)
    private static final rpc.RpcMedication.Empty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rpc.RpcMedication.Empty();
    }

    public static rpc.RpcMedication.Empty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Empty>
        PARSER = new com.google.protobuf.AbstractParser<Empty>() {
      @java.lang.Override
      public Empty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Empty(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Empty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Empty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public rpc.RpcMedication.Empty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Patient_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Patient_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Med_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Med_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Taken_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Taken_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024rpc_medication.proto\"\034\n\007Patient\022\021\n\tpat" +
      "ientId\030\001 \001(\003\":\n\003Med\022\017\n\007medName\030\001 \001(\t\022\021\n\t" +
      "startHour\030\002 \001(\t\022\017\n\007endHour\030\003 \001(\t\"<\n\005Take" +
      "n\022\017\n\007medName\030\001 \001(\t\022\021\n\tpatientId\030\002 \001(\003\022\017\n" +
      "\007isTaken\030\003 \001(\010\"\007\n\005Empty2Z\n\nMedication\022%\n" +
      "\021GetMedicationPlan\022\010.Patient\032\004.Med0\001\022%\n\023" +
      "SendMedicationTaken\022\006.Taken\032\006.EmptyB\005\n\003r" +
      "pcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Patient_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Patient_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Patient_descriptor,
        new java.lang.String[] { "PatientId", });
    internal_static_Med_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Med_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Med_descriptor,
        new java.lang.String[] { "MedName", "StartHour", "EndHour", });
    internal_static_Taken_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Taken_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Taken_descriptor,
        new java.lang.String[] { "MedName", "PatientId", "IsTaken", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
